import { StyleSheet } from '@react-pdf/renderer';

export const PDF_COLORS = {
  emerald: '#059669',
  rose: '#e11d48',
  indigo: '#6366f1',
  sky: '#0284c7',
  amber: '#d97706',
  slate: '#0f172a',
  muted: '#64748b',
  border: '#e2e8f0',
  panel: '#f8fafc',
  panelAlt: '#f1f5f9',
  white: '#ffffff',
  income: '#059669',
  expense: '#e11d48',
  investment: '#6366f1',
  transfer: '#0284c7',
};

export const PDF_FONT = 'Inter';

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 52,
    paddingHorizontal: 40,
    fontFamily: PDF_FONT,
    fontSize: 9,
    color: PDF_COLORS.slate,
    lineHeight: 1.45,
  },
  coverPage: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  coverAccent: {
    width: 48,
    height: 4,
    backgroundColor: PDF_COLORS.emerald,
    borderRadius: 2,
    marginBottom: 20,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    gap: 10,
  },
  brandMark: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: PDF_COLORS.emerald,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandMarkText: {
    color: PDF_COLORS.white,
    fontSize: 13,
    fontWeight: 700,
  },
  brand: {
    fontSize: 11,
    color: PDF_COLORS.emerald,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    fontWeight: 600,
  },
  coverTitle: {
    fontSize: 30,
    fontWeight: 700,
    marginBottom: 8,
    color: PDF_COLORS.slate,
  },
  coverSubtitle: {
    fontSize: 14,
    color: PDF_COLORS.muted,
    marginBottom: 28,
  },
  coverMeta: {
    fontSize: 10,
    color: PDF_COLORS.muted,
    marginBottom: 5,
  },
  tocBox: {
    marginTop: 28,
    padding: 14,
    backgroundColor: PDF_COLORS.panel,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
  },
  tocTitle: {
    fontSize: 10,
    fontWeight: 700,
    marginBottom: 8,
    color: PDF_COLORS.slate,
  },
  tocItem: {
    fontSize: 9,
    color: PDF_COLORS.muted,
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: PDF_COLORS.slate,
    marginTop: 16,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.border,
  },
  subsectionTitle: {
    fontSize: 11,
    fontWeight: 600,
    marginTop: 12,
    marginBottom: 6,
    color: PDF_COLORS.slate,
  },
  paragraph: {
    fontSize: 9,
    color: PDF_COLORS.muted,
    marginBottom: 8,
  },
  kpiRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  kpiCard: {
    width: '23%',
    minWidth: 110,
    padding: 10,
    backgroundColor: PDF_COLORS.panel,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
  },
  kpiLabel: {
    fontSize: 7.5,
    color: PDF_COLORS.muted,
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  kpiValue: {
    fontSize: 12,
    fontWeight: 700,
  },
  table: {
    marginBottom: 10,
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
    borderRadius: 6,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: PDF_COLORS.panel,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.border,
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.border,
  },
  tableRowAlt: {
    backgroundColor: PDF_COLORS.panelAlt,
  },
  tableHeaderCell: {
    fontSize: 7.5,
    fontWeight: 700,
    color: PDF_COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  tableCell: {
    fontSize: 8.5,
    color: PDF_COLORS.slate,
  },
  barTrack: {
    height: 7,
    backgroundColor: PDF_COLORS.border,
    borderRadius: 4,
    marginTop: 3,
    marginBottom: 8,
  },
  barFill: {
    height: 7,
    borderRadius: 4,
  },
  footer: {
    position: 'absolute',
    bottom: 22,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: 8,
    color: PDF_COLORS.muted,
    borderTopWidth: 1,
    borderTopColor: PDF_COLORS.border,
    paddingTop: 8,
  },
  footerBrand: {
    fontWeight: 600,
    color: PDF_COLORS.emerald,
  },
  amountIncome: {
    color: PDF_COLORS.income,
    fontWeight: 600,
  },
  amountExpense: {
    color: PDF_COLORS.expense,
    fontWeight: 600,
  },
  amountInvestment: {
    color: PDF_COLORS.investment,
    fontWeight: 600,
  },
  amountTransfer: {
    color: PDF_COLORS.transfer,
    fontWeight: 600,
  },
  clearedBadge: {
    fontSize: 7,
    color: PDF_COLORS.emerald,
    fontWeight: 600,
  },
  pendingBadge: {
    fontSize: 7,
    color: PDF_COLORS.amber,
    fontWeight: 600,
  },
});
